# CAR config
elastic:
  hosts: [http://localhost:9200]
  http_auth: [elastic, password]
  index: [winevents-*]
translator:
  mappings: ../config/car-car.yml
  wildcard_suffix: .keyword
  wildcard_suffix_fields: [script_block_text, call_trace, file_path]
  escaped_fields: [data_model.fields.image_path, data_model.fields.parent_image_path]
detector:
  # start: 2024-04-01T00:00:00.000Z
  # end: 2024-04-02T00:00:00.000Z
  interval: 10.0
web:
  port: 8089
